name = "prime"
pages_build_output_dir = "out"
compatibility_date = "2025-06-20"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "f3d56007e07d494cb3ab0db1995fd958"
preview_id = "f49512da7ac246e7bac8d97375a42809"

[vars]
# Set real values in Cloudflare Pages env configuration.
CF_FIREBASE_DATABASE_URL = "https://example.firebaseio.com"

# Set as a Cloudflare secret, not in source control:
# wrangler secret put CF_FIREBASE_API_KEY
