name = "base-shop"
pages_build_output_dir = ".vercel/output/static"
compatibility_date    = "2025-06-20"

[[kv_namespaces]]
binding = "CART_KV"
id = "0e0888a980cd46efa1d28aea3794b3ac"
preview_id = "f10f858acbb0429da3910894c9151560"

[vars]
  NEXT_PUBLIC_SHOP_ID = "default"
  CART_TTL = "2592000"

[[r2_buckets]]
binding = "TRYON_R2"
bucket_name = "base-shop-tryon"

# (Optional) Enable KV for idempotency/quotas later
# [[kv_namespaces]]
# binding = "TRYON_KV"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
