name: Deploy Prime

on:
  push:
    branches:
      - main
      - staging
    paths:
      - 'apps/prime/**'
      - 'packages/design-system/**'
      - 'packages/design-tokens/**'
      - 'packages/next-config/**'
      - 'packages/tailwind-config/**'
      - 'packages/themes/**'
      - 'packages/ui/**'
      - '.github/workflows/prime.yml'
      - '.github/workflows/reusable-app.yml'
  pull_request:
    paths:
      - 'apps/prime/**'
      - 'packages/design-system/**'
      - 'packages/design-tokens/**'
      - 'packages/next-config/**'
      - 'packages/tailwind-config/**'
      - 'packages/themes/**'
      - 'packages/ui/**'
      - '.github/workflows/prime.yml'
      - '.github/workflows/reusable-app.yml'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/reusable-app.yml
    with:
      app-filter: "@apps/prime"
      build-cmd: >
        OUTPUT_EXPORT=1
        NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
        NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
        NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
        NEXT_PUBLIC_FIREBASE_DATABASE_URL=${{ secrets.NEXT_PUBLIC_FIREBASE_DATABASE_URL }}
        NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID }}
        pnpm --filter @apps/prime... build
      artifact-path: apps/prime/out
      deploy_cmd: >
        cd apps/prime &&
        pnpm exec wrangler pages deploy out
        --project-name prime
        --branch ${{ github.ref_name }}
      deploy_enabled: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging') }}
      test-shard-count: 3
      project-name: "prime"
      environment-name: "${{ github.ref_name == 'staging' && 'staging' || 'production' }}"
      environment-url: "${{ github.ref_name == 'staging' && 'https://staging.prime-egt.pages.dev' || 'https://prime-egt.pages.dev' }}"
      healthcheck-args: "${{ github.ref_name == 'staging' && '--staging' || '' }}"
    secrets: inherit
