name: Deploy Prime

on:
  push:
    branches:
      - main
    paths:
      - 'apps/prime/**'
      - 'packages/design-system/**'
      - 'packages/design-tokens/**'
      - 'packages/next-config/**'
      - 'packages/tailwind-config/**'
      - 'packages/themes/**'
      - 'packages/ui/**'
      - '.github/workflows/prime.yml'
  pull_request:
    paths:
      - 'apps/prime/**'
      - 'packages/design-system/**'
      - 'packages/design-tokens/**'
      - 'packages/next-config/**'
      - 'packages/tailwind-config/**'
      - 'packages/themes/**'
      - 'packages/ui/**'
      - '.github/workflows/prime.yml'
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/reusable-app.yml
    with:
      app-filter: "@apps/prime"
      build-cmd: OUTPUT_EXPORT=1 pnpm --filter @apps/prime... build
      artifact-path: apps/prime/out
      deploy-cmd: >
        pnpm exec wrangler pages deploy apps/prime/out
        --project-name prime
        --branch ${{ github.ref_name }}
        --functions apps/prime/functions
      project-name: "prime"
    secrets: inherit
